services:
  app:
    image: cimg/go:1.22
    environment:
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
    volumes:
      - type: bind
        source: ./
        target: /home/circleci/project
    command: /bin/sh -c "go install github.com/air-verse/air@latest && air --build.cmd 'go build -o ./bin/server' --build.bin ./bin/server --build.send_interrupt true --build.kill_delay 9000 --build.exclude_dir front"
    ports:
      - "8080:8080"
  front:
    image: cimg/node:23.4.0
    environment:
      - NEXT_PUBLIC_API_URL
    command: npm run dev
    volumes:
      - type: bind
        source: ./front
        target: /home/circleci/project
    ports:
      - "3000:3000"
