services:
  app:
    image: cimg/go:1.22
    volumes:
      - type: bind
        source: ./
        target: /home/circleci/project
    command: /bin/sh -c "go install github.com/air-verse/air@latest && air --build.cmd 'go build -o ./bin/server' --build.bin ./bin/server --build.send_interrupt true"
    ports:
      - "8080:8080"
